#ifndef GAMEMENU_H
#define GAMEMENU_H

enum menu_ID {

    MENU_ID_VIDMODE,

    MENU_ID_BUMPREF_ON,
    MENU_ID_BUMPREF_OFF,

    MENU_ID_BUMPWOOD_ON,
    MENU_ID_BUMPWOOD_OFF,

    MENU_ID_BALLTRACE_ON,
    MENU_ID_BALLTRACE_OFF,

    MENU_ID_REFLECTION_SPHERE,
    MENU_ID_REFLECTION_RENDERED,
    MENU_ID_REFLECTION_RENDERED_FRESNEL,

    MENU_ID_BALL_DETAIL_LOW,
    MENU_ID_BALL_DETAIL_MED,
    MENU_ID_BALL_DETAIL_HIGH,
    MENU_ID_BALL_DETAIL_VERYHIGH,

    MENU_ID_RGAIM_MIDDLE,
    MENU_ID_RGAIM_LEFT,
    MENU_ID_RGAIM_RIGHT,

    MENU_ID_RGSTEREO_OFF,
    MENU_ID_RGSTEREO_ON,

    MENU_ID_LENSFLARE_OFF,
    MENU_ID_LENSFLARE_ON,

    MENU_ID_FULLSCREEN_ON,
    MENU_ID_FULLSCREEN_OFF,

    MENU_ID_GAMETYPE_8BALL,
    MENU_ID_GAMETYPE_9BALL,
    MENU_ID_GAMETYPE_CARAMBOL,
    MENU_ID_GAMETYPE_SNOOKER,

    MENU_ID_TABLETHEME_GOLDGREEN,
    MENU_ID_TABLETHEME_GOLDRED,
    MENU_ID_TABLETHEME_CHROMEBLUE,
    MENU_ID_TABLETHEME_BLACKBEIGE,
    MENU_ID_TABLETHEME_BLACKWHITE,

    MENU_ID_TABLESIZE_7FOOT,
    MENU_ID_TABLESIZE_8FOOT,
    MENU_ID_TABLESIZE_9FOOT,
    MENU_ID_TABLESIZE_12FOOT,

    MENU_ID_HELPLINE_ON,
    MENU_ID_HELPLINE_OFF,

    MENU_ID_NETWORK_HOST,
    MENU_ID_NETWORK_JOIN,
    MENU_ID_NETWORK_IP,
    MENU_ID_NETWORK_PORTNUM,

    MENU_ID_OPTIONS_DISPLAY,
    MENU_ID_OPTIONS_SOUND,
    MENU_ID_OPTIONS_GAME,

    MENU_ID_MAIN_RESUME,
    MENU_ID_MAIN_RESTART,
    MENU_ID_MAIN_HELP,
    MENU_ID_MAIN_QUIT,

    MENU_ID_PLAYER1_NAME,
    MENU_ID_PLAYER2_NAME,

    MENU_ID_PLAYER1_TYPE_AI,
    MENU_ID_PLAYER2_TYPE_AI,
    MENU_ID_PLAYER1_TYPE_HUMAN,
    MENU_ID_PLAYER2_TYPE_HUMAN,

    MENU_ID_PLAYER1_SKILL_EXCEL,
    MENU_ID_PLAYER1_SKILL_GOOD,
    MENU_ID_PLAYER1_SKILL_MEDIUM,
    MENU_ID_PLAYER1_SKILL_BAD,
    MENU_ID_PLAYER1_SKILL_WORSE,
    MENU_ID_PLAYER2_SKILL_EXCEL,
    MENU_ID_PLAYER2_SKILL_GOOD,
    MENU_ID_PLAYER2_SKILL_MEDIUM,
    MENU_ID_PLAYER2_SKILL_BAD,
    MENU_ID_PLAYER2_SKILL_WORSE,

    MENU_ID_GAMEMODE_MATCH,
    MENU_ID_GAMEMODE_TOURNAMENT,
    MENU_ID_GAMEMODE_TRAINING,

    MENU_ID_SINGLE_MATCH_START,
    MENU_ID_TOURNAMENT_START,
    MENU_ID_TRAINING_START,

    MENU_ID_IDLE
};

#endif
